/*
 * WARNING: This migration file was auto-generated by @anclatechs/sql-buns-migrate
 * on November 2, 2025 (version 1.0.0).
 *
 * Do not edit this file manually, as it may complicate the migration process
 * or lead to unexpected issues. If changes are needed, regenerate the file
 * or modify the source configuration instead. Only proceed with direct edits
 * if you are absolutely certain of the implications.
 */
import { pool } from "@anclatechs/sql-buns";
export async function up() {/**Go to file: 1762103093445_new.sql*/}
export async function down() {
  await pool.run(``);
}
  