-- Baseline migration (auto-generated by @anclatechs/sql-buns-migrate :: inspectdb)
-- On November 23, 2025 (version 1.0.0)
-- Modified to ensure backward compatibility with previous installation running with prisma.

PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users_new (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users_new (id, username, email, password, created_at, updated_at)
SELECT id, username, email, password, created_at, updated_at
FROM users;

DROP TABLE users;
ALTER TABLE users_new RENAME TO users;

-- PROJECT

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id),
  current_head TEXT,
  app_local_path TEXT,
  app_url TEXT,
  repository_url TEXT,
  tcp_port TEXT,
  log_file_i_location TEXT,
  log_file_ii_location TEXT,
  log_file_iii_location TEXT,
  pipeline_json TEXT
);

CREATE TABLE IF NOT EXISTS projects_new (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id),
  current_head TEXT,
  app_local_path TEXT,
  app_url TEXT,
  repository_url TEXT,
  tcp_port TEXT,
  log_file_i_location TEXT,
  log_file_ii_location TEXT,
  log_file_iii_location TEXT,
  pipeline_json TEXT
);

INSERT INTO projects_new (
  id, user_id, current_head, app_local_path, app_url, repository_url,
  tcp_port, log_file_i_location, log_file_ii_location, log_file_iii_location, pipeline_json
)
SELECT id, user_id, current_head, app_local_path, app_url, repository_url,
       tcp_port, log_file_i_location, log_file_ii_location, log_file_iii_location, pipeline_json
FROM projects;

DROP TABLE projects;
ALTER TABLE projects_new RENAME TO projects;

-- DEPLOYMENTS

CREATE TABLE IF NOT EXISTS deployments (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id),
  project_id INTEGER NOT NULL REFERENCES projects(id),
  commit_hash TEXT NOT NULL,
  action TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME,
  log_output TEXT,
  artifact_path TEXT,
  pipeline_stage_uuid TEXT
);

CREATE TABLE IF NOT EXISTS deployments_new (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id),
  project_id INTEGER NOT NULL REFERENCES projects(id),
  commit_hash TEXT NOT NULL,
  action TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME,
  log_output TEXT,
  artifact_path TEXT,
  pipeline_stage_uuid TEXT
);

INSERT INTO deployments_new (
  id, user_id, project_id, commit_hash, action, status,
  started_at, finished_at, log_output, artifact_path, pipeline_stage_uuid
)
SELECT id, user_id, project_id, commit_hash, action, status,
       started_at, finished_at, log_output, artifact_path, pipeline_stage_uuid
FROM deployments;

DROP TABLE deployments;
ALTER TABLE deployments_new RENAME TO deployments;


-- ACTIVITY LOG

CREATE TABLE IF NOT EXISTS activity_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  project_id INTEGER NOT NULL REFERENCES projects(id),
  deployment_id INTEGER REFERENCES deployments(id),
  action TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activity_logs_new (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  project_id INTEGER NOT NULL REFERENCES projects(id),
  deployment_id INTEGER REFERENCES deployments(id),
  action TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO activity_logs_new (id, project_id, deployment_id, action, message, created_at)
SELECT id, project_id, deployment_id, action, message, created_at
FROM activity_logs;

DROP TABLE activity_logs;
ALTER TABLE activity_logs_new RENAME TO activity_logs;


-- SAFE CREATIONS

CREATE TABLE IF NOT EXISTS managed_redis_server (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  port INTEGER NOT NULL,
  metadata TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS _prisma_migrations (
  id TEXT PRIMARY KEY NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS _sqlbuns_migrations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  checksum VARCHAR(64) NOT NULL,
  previous_checksum VARCHAR(64),
  direction VARCHAR(10) NOT NULL DEFAULT 'up',
  applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  rolled_back INTEGER DEFAULT 0,
  rolled_back_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects (user_id);
CREATE INDEX IF NOT EXISTS idx_deployments_user_id ON deployments (user_id);
CREATE INDEX IF NOT EXISTS idx_deployments_project_id ON deployments (project_id);

PRAGMA foreign_keys = ON;