-- Baseline migration (auto-generated by @anclatechs/sql-buns-migrate :: inspectdb)
-- On November 23, 2025 (version 1.0.0)
CREATE TABLE IF NOT EXISTS "users" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  updated_at DATETIME DEFAULT 'CURRENT_TIMESTAMP'
);
ALTER TABLE projects ADD CONSTRAINT fk_projects_user_id FOREIGN KEY (user_id) REFERENCES users(id);
CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects (user_id);
ALTER TABLE deployments ADD CONSTRAINT fk_deployments_user_id FOREIGN KEY (user_id) REFERENCES users(id);
CREATE INDEX IF NOT EXISTS idx_deployments_user_id ON deployments (user_id);
CREATE TABLE IF NOT EXISTS "projects" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL,
  current_head TEXT,
  app_local_path TEXT,
  app_url TEXT,
  repository_url TEXT,
  tcp_port TEXT,
  log_file_i_location TEXT,
  log_file_ii_location TEXT,
  log_file_iii_location TEXT,
  pipeline_json TEXT
);
ALTER TABLE deployments ADD CONSTRAINT fk_deployments_project_id FOREIGN KEY (project_id) REFERENCES projects(id);
CREATE INDEX IF NOT EXISTS idx_deployments_project_id ON deployments (project_id);
CREATE TABLE IF NOT EXISTS "deployments" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL,
  project_id INTEGER NOT NULL,
  commit_hash TEXT NOT NULL,
  action TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  finished_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  log_output TEXT,
  artifact_path TEXT,
  pipeline_stage_uuid TEXT
);
CREATE TABLE IF NOT EXISTS "activity_logs" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  project_id INTEGER NOT NULL,
  deployment_id INTEGER,
  action TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  FOREIGN KEY (project_id) REFERENCES projects(id),
  FOREIGN KEY (deployment_id) REFERENCES deployments(id)
);
CREATE TABLE IF NOT EXISTS "managed_redis_server" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  port INTEGER NOT NULL,
  metadata TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP'
);
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id TEXT NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  started_at DATETIME NOT NULL DEFAULT 'current_timestamp',
  applied_steps_count INTEGER NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS "_sqlbuns_migrations" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  checksum VARCHAR(64) NOT NULL,
  previous_checksum VARCHAR(64),
  direction VARCHAR(10) NOT NULL DEFAULT 'up',
  applied_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  rolled_back INTEGER DEFAULT '0',
  rolled_back_at DATETIME DEFAULT 'CURRENT_TIMESTAMP'
);