/*
* WARNING: This migration file was auto-generated by @anclatechs/sql-buns-migrate
* on November 23, 2025 (version 1.0.0).
*
* Do not edit this file manually, as it may complicate the migration process
* or lead to unexpected issues. If changes are needed, regenerate the file
* or modify the source configuration instead. Only proceed with direct edits
* if you are absolutely certain of the implications.
*/
import { pool } from "@anclatechs/sql-buns";
export async function up() {/**Go to file: 1763920845546_0000_initial_inspectdb.sql*/}
export async function down() {
  await pool.run(`DROP TABLE IF EXISTS users;
DROP INDEX IF EXISTS idx_projects_user_id;
ALTER TABLE projects DROP CONSTRAINT fk_projects_user_id;
DROP INDEX IF EXISTS idx_deployments_user_id;
ALTER TABLE deployments DROP CONSTRAINT fk_deployments_user_id;
DROP TABLE IF EXISTS projects;
DROP INDEX IF EXISTS idx_deployments_project_id;
ALTER TABLE deployments DROP CONSTRAINT fk_deployments_project_id;
DROP TABLE IF EXISTS deployments;
DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS managed_redis_server;
DROP TABLE IF EXISTS _prisma_migrations;
DROP TABLE IF EXISTS _sqlbuns_migrations;`);
}