/*
 * WARNING: This migration file was auto-generated by @anclatechs/sql-buns-migrate
 * on November 23, 2025 (version 1.0.0).
 *
 * Do not edit this file manually, as it may complicate the migration process
 * or lead to unexpected issues. If changes are needed, regenerate the file
 * or modify the source configuration instead. Only proceed with direct edits
 * if you are absolutely certain of the implications.
 */
import { pool } from "@anclatechs/sql-buns";
export async function up() {/**Go to file: 1763921726061_remove_prisma.sql*/}
export async function down() {
  await pool.run(`CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id TEXT NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  started_at DATETIME NOT NULL DEFAULT 'current_timestamp',
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id TEXT NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  started_at DATETIME NOT NULL DEFAULT 'current_timestamp',
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id TEXT NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  started_at DATETIME NOT NULL DEFAULT 'current_timestamp',
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id TEXT NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  started_at DATETIME NOT NULL DEFAULT 'current_timestamp',
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id TEXT NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  started_at DATETIME NOT NULL DEFAULT 'current_timestamp',
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id TEXT NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT 'CURRENT_TIMESTAMP',
  started_at DATETIME NOT NULL DEFAULT 'current_timestamp',
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);`);
}
  