-- Baseline migration (auto-generated by @anclatechs/sql-buns-migrate :: inspectdb)
-- On November 23, 2025 (version 1.0.0)
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='users') THEN
    -- Check if all required columns exist
    IF NOT EXISTS (
      SELECT 1 FROM pragma_table_info('users') WHERE name IN ('id','username','email','password','created_at','updated_at')
    ) THEN
      EXECUTE 'ALTER TABLE users RENAME TO users_old';
      RAISE NOTICE 'users table had missing columns → migrating data';
    END IF;
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "users" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO users (id, username, email, password, created_at, updated_at)
SELECT id, username, email, password, created_at, updated_at
FROM users_old;

DROP TABLE IF EXISTS users_old;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='projects') THEN
    IF NOT EXISTS (SELECT 1 FROM pragma_table_info('projects') WHERE name='user_id')
       OR NOT EXISTS (SELECT 1 FROM pragma_table_info('projects') WHERE name='current_head') THEN
      EXECUTE 'ALTER TABLE projects RENAME TO projects_old';
    END IF;
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "projects" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL,
  current_head TEXT,
  app_local_path TEXT,
  app_url TEXT,
  repository_url TEXT,
  tcp_port TEXT,
  log_file_i_location TEXT,
  log_file_ii_location TEXT,
  log_file_iii_location TEXT,
  pipeline_json TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT OR IGNORE INTO projects 
  (id, user_id, current_head, app_local_path, app_url, repository_url, tcp_port,
   log_file_i_location, log_file_ii_location, log_file_iii_location, pipeline_json)
SELECT id, user_id, current_head, app_local_path, app_url, repository_url, tcp_port,
       log_file_i_location, log_file_ii_location, log_file_iii_location, pipeline_json
FROM projects_old;

DROP TABLE IF EXISTS projects_old;


DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='deployments') THEN
    IF NOT EXISTS (SELECT 1 FROM pragma_table_info('deployments') WHERE name='pipeline_stage_uuid') THEN
      EXECUTE 'ALTER TABLE deployments RENAME TO deployments_old';
    END IF;
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "deployments" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL,
  project_id INTEGER NOT NULL,
  commit_hash TEXT NOT NULL,
  action TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  log_output TEXT,
  artifact_path TEXT,
  pipeline_stage_uuid TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (project_id) REFERENCES projects(id)
);

INSERT OR IGNORE INTO deployments 
  (id, user_id, project_id, commit_hash, action, status, started_at, finished_at,
   log_output, artifact_path, pipeline_stage_uuid)
SELECT id, user_id, project_id, commit_hash, action, status, started_at, finished_at,
       log_output, artifact_path, pipeline_stage_uuid
FROM deployments_old;

DROP TABLE IF EXISTS deployments_old;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='activity_logs') THEN
    EXECUTE 'ALTER TABLE activity_logs RENAME TO activity_logs_old';
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "activity_logs" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  project_id INTEGER NOT NULL,
  deployment_id INTEGER,
  action TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id),
  FOREIGN KEY (deployment_id) REFERENCES deployments(id)
);

INSERT OR IGNORE INTO activity_logs (id, project_id, deployment_id, action, message, created_at)
SELECT id, project_id, deployment_id, action, message, created_at
FROM activity_logs_old;

DROP TABLE IF EXISTS activity_logs_old;

CREATE TABLE IF NOT EXISTS "managed_redis_server" (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  port INTEGER NOT NULL,
  metadata TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id TEXT PRIMARY KEY NOT NULL,
  checksum TEXT NOT NULL,
  finished_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  migration_name TEXT NOT NULL,
  logs TEXT,
  rolled_back_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE IF NOT EXISTS "_sqlbuns_migrations" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  checksum VARCHAR(64) NOT NULL,
  previous_checksum VARCHAR(64),
  direction VARCHAR(10) NOT NULL DEFAULT 'up',
  applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  rolled_back INTEGER DEFAULT 0,
  rolled_back_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects (user_id);
CREATE INDEX IF NOT EXISTS idx_deployments_user_id ON deployments (user_id);
CREATE INDEX IF NOT EXISTS idx_deployments_project_id ON deployments (project_id);

COMMIT;

PRAGMA foreign_keys = ON;