const DEPLOYMENT_STATUS = {
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

const DEPLOYMENT_ACTION_TYPE = {
  DEPLOY: "DEPLOY",
  ROLLBACK: "ROLLBACK",
};

module.exports = {
  DEPLOYMENT_STATUS,
  DEPLOYMENT_ACTION_TYPE,
};
