export const DEPLOYMENT_STATUS = {
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export const DEPLOYMENT_ACTION_TYPE = {
  DEPLOY: "DEPLOY",
  ROLLBACK: "ROLLBACK",
};

export const PASSWORD_TTL = 10 * 60;
export const PG_PASSWORD_KEY = "PG_PASSWORD";
export const PG_USERNAME_KEY = "PG_USERNAME";
export const PG_CLUSTER = "PG_CLUSTER_VERSION";
